#!/usr/bin/bash

chalName=$1

if [ -z "$chalName" ]; then
    echo "Usage: ./setup <chal name>"
    exit 1
fi

if [ -d "./$chalName" ]; then
    echo "Challenge \"$chalName\" already setup"
    exit 1

# Check challenge exists
status=$(curl -s -I https://open.kattis.com/problems/$chalName | head -n 1 | cut -d " " -f 2)

if [ ! $status -ne "200" ]; then
    echo "Challenge \"$chalName\" doesn't exist"
    exit 1

# Setup challenge folder
mkdir $1
cp Main.java ./$1/
cp test ./$1/
cd ./$1/

# Download tests files
curl -s -o samples.zip "https://open.kattis.com/problems/$chalName/file/statement/samples.zip"
unzip samples.zip
rm samples.zip

exit 0
