#!/bin/bash

chalName=$1

if [ -z "$chalName" ]; then
    echo "Usage: . ./setup <challenge id>"
    return
fi

if [ -d "./$chalName" ]; then
    echo "Challenge \"$chalName\" already setup"
    return
fi

# Check challenge exists
statusCode=$(curl -s -I https://open.kattis.com/problems/$chalName | head -n 1 | cut -d " " -f 2)

if [ $statusCode -ne "200" ]; then
    echo "Challenge \"$chalName\" doesn't exist"
    return
fi

# Setup challenge folder
mkdir $1
cp Main.java ./$1/
cd ./$1/

# Download tests files
curl -s -o samples.zip "https://open.kattis.com/problems/$chalName/file/statement/samples.zip"
unzip samples.zip 1>/dev/null
rm samples.zip

echo Challenge setup successfully!
