#!/bin/bash

javac Main.java

# Check failed compilation
if [ $? -ne 0 ]; then
    echo "[ERR] Failed to compile"
    return
fi

testIn=()
while IFS=  read -r -d $'\0'; do
    testIn+=("$REPLY")
done < <(find . -name "*.in" -print0)

for i in $testIn; do
    fileName=$(echo $i | cut -d "." -f 2 | cut -d "/" -f 2)
    echo Testing: $fileName
    java Main < $fileName.in > $fileName.out
    diff -y $fileName.out $fileName.ans
    if [ $? -eq 1 ]; then
        echo "[ERR] Failed test case $fileName"
        return
    fi
done

echo "[SUCCESS] All test cases passed!"

